version: '3.8'
services:

  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - '3308:3308'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${MYSQL_HOST} -u root -p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3308
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
    - 3333:3333
    depends_on:
      - db

volumes:
  db:
